title: Vinícius Mesel
email: vinicius@bigsp.com.br
description: "Este é um blog sobre desenvolvimento de software livre, gerenciamento de servidores e tudo o que der na telha"
baseurl: ""
url: ""
twitter_username: vmesel
github_username:  vmesel
markdown: kramdown
